"""create data core tables

Revision ID: 81f11f6f6071
Revises: 
Create Date: 2026-10-08 12:43:22.182061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '81f11f6f6071'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='URL·파일명에 쓰는 고유 식별자'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='표시 제목'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False, comment='생성 시각(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    comment='데이터 묶음(주제 1개 단위)',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('dataset_schemas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False, comment='소속 데이터 묶음'),
    sa.Column('version', sa.Integer(), nullable=False, comment='정의 버전(묶음 안에서 증가)'),
    sa.Column('fields', sa.JSON(), nullable=False, comment='필드 정의 배열(원소 1개 = 칸 1개)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False, comment='생성 시각(UTC)'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version', name='uq_dataset_schemas_dataset_version'),
    comment='데이터 묶음의 필드 정의 이력',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False, comment='소속 데이터 묶음'),
    sa.Column('schema_id', sa.BigInteger(), nullable=False, comment='버전이 따르는 필드 정의'),
    sa.Column('version_no', sa.Integer(), nullable=False, comment='버전 번호(묶음 안에서 증가)'),
    sa.Column('note', sa.String(length=500), nullable=True, comment='버전 메모'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False, comment='생성 시각(UTC)'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['schema_id'], ['dataset_schemas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version_no', name='uq_dataset_versions_dataset_version_no'),
    comment='승인 행을 묶은 데이터 버전',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('imports',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False, comment='대상 데이터 묶음'),
    sa.Column('schema_id', sa.BigInteger(), nullable=False, comment='검사에 쓴 필드 정의'),
    sa.Column('source_type', sa.Enum('upload', 'claude', 'api', name='import_source_type'), nullable=False, comment='입력 경로: upload | claude | api'),
    sa.Column('raw_payload', mysql.LONGTEXT(), nullable=False, comment='입력 원문 그대로'),
    sa.Column('default_source_url', sa.String(length=2048), nullable=True, comment='행에 출처 URL이 없을 때 쓰는 기본 출처'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False, comment='생성 시각(UTC)'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['schema_id'], ['dataset_schemas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='입력 1회분 원본(업로드·붙여넣기 등)',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('dataset_rows',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=False, comment='소속 데이터 묶음'),
    sa.Column('import_id', sa.BigInteger(), nullable=False, comment='이 행을 만든 입력'),
    sa.Column('row_key', sa.String(length=191), nullable=False, comment='key 필드 값을 정의 순서대로 | 로 연결한 값'),
    sa.Column('data', sa.JSON(), nullable=False, comment='정규화된 칸 값'),
    sa.Column('source_kind', sa.Enum('external', 'self', name='row_source_kind'), nullable=True, comment='출처 유형: external | self (누락 시 승인 불가)'),
    sa.Column('source_url', sa.String(length=2048), nullable=True, comment='출처 URL'),
    sa.Column('as_of_date', sa.Date(), nullable=True, comment='출처 기준 날짜'),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='row_status'), server_default='pending', nullable=False, comment='검토 상태: pending | approved | rejected'),
    sa.Column('errors', sa.JSON(), nullable=True, comment='검사 오류 목록 [{code, field, message}]'),
    sa.Column('reject_reason', sa.String(length=500), nullable=True, comment='반려 사유'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='검토 시각(UTC)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False, comment='생성 시각(UTC)'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['imports.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='검사를 거친 데이터 행(값은 JSON)',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_dataset_rows_dataset_row_key', 'dataset_rows', ['dataset_id', 'row_key'], unique=False)
    op.create_table('dataset_version_rows',
    sa.Column('version_id', sa.BigInteger(), nullable=False, comment='데이터 버전'),
    sa.Column('row_id', sa.BigInteger(), nullable=False, comment='포함된 행'),
    sa.ForeignKeyConstraint(['row_id'], ['dataset_rows.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['dataset_versions.id'], ),
    sa.PrimaryKeyConstraint('version_id', 'row_id'),
    comment='버전에 포함된 행 목록',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dataset_version_rows')
    # ix_dataset_rows_dataset_row_key 는 dataset_id FK 가 쓰는 인덱스라 단독 DROP INDEX 가 거부된다. 테이블과 함께 지운다.
    op.drop_table('dataset_rows')
    op.drop_table('imports')
    op.drop_table('dataset_versions')
    op.drop_table('dataset_schemas')
    op.drop_table('datasets')
    # ### end Alembic commands ###
