"""story publish tables

Revision ID: a0ab567cbc5a
Revises: b57a20ec6c6a
Create Date: 2026-10-09 16:51:03.489423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0ab567cbc5a'
down_revision: Union[str, Sequence[str], None] = 'b57a20ec6c6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

SEED_LOCK_ROW = sa.text("INSERT INTO story_publish_lock (id) VALUES (1)")


def upgrade() -> None:
    """이야기 · 이야기 판 · 발행 잠금 테이블을 만들고 잠금 행을 넣는다."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False, comment='이야기 주소 이름(stories/{slug}.json)'),
    sa.Column('first_published_at', sa.DateTime(), nullable=True, comment='처음 공개된 시각(UTC)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False, comment='생성 시각(UTC)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    comment='발행하는 이야기',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('story_publish_lock',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.CheckConstraint('id = 1', name='ck_story_publish_lock_single_row'),
    sa.PrimaryKeyConstraint('id'),
    comment='이야기 발행 전역 잠금(1행)',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('story_versions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('story_id', sa.BigInteger(), nullable=False, comment='소속 이야기'),
    sa.Column('version_no', sa.Integer(), nullable=False, comment='판 번호(이야기 안에서 증가)'),
    sa.Column('title', sa.String(length=60), nullable=False, comment='이야기 제목'),
    sa.Column('summary', sa.String(length=200), nullable=False, comment='목록 요약'),
    sa.Column('datasets', sa.JSON(), nullable=False, comment='묶음 주소 이름 → 데이터 판 번호'),
    sa.Column('publish_status', sa.Enum('pending', 'done', 'failed', 'abandoned', name='publish_status'), server_default='pending', nullable=False, comment='이야기 파일 상태: pending | done | failed'),
    sa.Column('published_at', sa.DateTime(), nullable=True, comment='이야기 파일 · 목록 교체 완료 시각(UTC)'),
    sa.Column('publish_error', sa.String(length=64), nullable=True, comment='발행 실패 오류 코드(경로 · 예외 문장 저장 금지)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False, comment='생성 시각(UTC)'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('story_id', 'version_no', name='uq_story_versions_story_version_no'),
    sa.CheckConstraint("publish_status IN ('pending', 'done', 'failed')", name='ck_story_versions_publish_status'),
    comment='이야기 발행 판(제목 · 요약 · 묶음 판)',
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
    # 잠금 행 1개를 넣는다. 발행은 이 행을 FOR UPDATE 로 잡아 줄 선다(D-37). 외부 값이 없는 고정 문장이라 바인딩할 매개변수가 없다.
    op.execute(SEED_LOCK_ROW)


def downgrade() -> None:
    """세 테이블을 지운다. 이야기 판 이력은 함께 사라진다(이미 쓴 이야기 파일 · 목록은 볼륨에 그대로 남는다)."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('story_versions')
    op.drop_table('story_publish_lock')
    op.drop_table('stories')
    # ### end Alembic commands ###
